#### Vectorization and BroadCasting

In [1]:
 import numpy as np

In [3]:
#Broadcasting
arr=np.array([1,2,3,4,5])
arr1=np.array([5])
print(arr+arr1)

[ 6  7  8  9 10]


#### we use BroadCasting when we are using Numpy array for an Operation and having Diffrences In Size
### You can See we are doing Array Addition
But One Array has diamension (1,5)
And  Other One is (5,)

In this case we are doing an Addition
how its Possible to add such array which is not compatible to add 
With the help of the BroadCasting 

it just scale the [5] into [5,5,5,5,5] & And then it add two Array

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

they are equal, or

one of them is 1.

In [6]:
a=np.array([1,2,3,4,5])
a1=np.array([[1,2,3,4,5],[2,2,2,2,2]])
print(a,a.shape)
print(a1,a1.shape)
print(a+a1)

[1 2 3 4 5] (5,)
[[1 2 3 4 5]
 [2 2 2 2 2]] (2, 5)
[[ 2  4  6  8 10]
 [ 3  4  5  6  7]]


In [7]:
b=np.array([[1,2,3,4,5],[2,2,2,2,2],[3,3,3,3,3]])
b1=np.array([[1,2,3,4,5],[2,2,2,2,2]])
print(b,b.shape)
print(b1,b1.shape)
print(b+b1)

[[1 2 3 4 5]
 [2 2 2 2 2]
 [3 3 3 3 3]] (3, 5)
[[1 2 3 4 5]
 [2 2 2 2 2]] (2, 5)


ValueError: operands could not be broadcast together with shapes (3,5) (2,5) 