##### Here we will discuss how to create Numpy Array and Diffrent Properpties which is Associated with Numpy

###### Lets create simple Numpy Array with the List

In [1]:
import numpy as np

In [2]:
np_arry1=np.array([1,2,3,4,5])
print(np_arry1)

[1 2 3 4 5]


In [5]:
#We can aslo print the type of the array
print(np_arry1,type(np_arry1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [8]:
#To print the dataType we aslo have an another way
print(np_arry1.dtype)

int32


In [12]:
#npArray store the data of homogenious type we cannot hv mix type of data in the npArray
#Suppose we have an Array Like 
arr2=np.array([1,2,3,4,5,6,"9"])
print(arr2,arr2.dtype)

['1' '2' '3' '4' '5' '6' '9'] <U11


In [13]:
#Our whole Array is converted into String to have homogenious Structure
#We can aslo Print the shape for npArray 
#Shape simply means Diamention

print(arr2.shape)


(7,)


In [16]:
#Lets create multiDiamentional Array

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.dtype)
print("shape of an Array Is",arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] int32
shape of an Array Is (3, 3)
