In [1]:
import numpy as np

#### We can aslo create numpy array from scratch
- np.zeros()  npArray prefill with 0
- np.onces()  npArray prefill with 1
- np.fill()   npArray prefill with particular Value
- np.arange() npArray prefill with range of Values



In [8]:
#Array with prefill with 0
arr1=np.zeros([2,3],dtype="int64")
print(arr1,arr1.dtype)

[[0 0 0]
 [0 0 0]] int64


In [10]:
#we can aslo set the tupe currently we have float
#Create an Array Prefill with 1
arr2=np.ones([2,3])
print(arr2)


[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#we can aslo prefill an Array with thr require values
arr3=np.full([2,3],22)
print(arr3)

[[22 22 22]
 [22 22 22]]


In [15]:
#eye create an Identity Matrix
arr4=np.eye(3)
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
#we can aslo create np Array with a range as we use with loop
arr5=np.arange(1,10,1)
print(arr5,arr5.shape)

[1 2 3 4 5 6 7 8 9] (9,)


In [20]:
#we can aslo create Evenly spaced array with linspace

arr6=np.linspace(1,100,3)
print(arr6)

[  1.   50.5 100. ]


##### Whenerver we create numpy Array there are Diffrent properties which associated with it

In [24]:
#shape which print diamentions
# size-->total element
#dtype -->data type 
#ndim -->
#if we have existing array and we want to convert it into another type we can use astype

arr=np.array([1,2,3,4,5])
print(arr,arr.dtype)

[1 2 3 4 5] int32


In [26]:
#to convert it 
newArr=arr.astype(np.float64)
print(newArr,newArr.dtype)

[1. 2. 3. 4. 5.] float64
