In [5]:
import numpy as np

### we can do diffrent Operations On the Numpy Array
- reshaping
- indexing 
- fancy and Boolean Indexing 
- Slicing 

 1 reshaping 

In [10]:
#reshaping means we can change the diamentions of an Array
#when we do reshaping its important to have the same size as we wanted to in desired diamentions
#You cannot change 2x3 to 2x5

arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [11]:
#lets conver the above into 3x2
newarr=arr.reshape((3,2))
print(newarr,newarr.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)


###### 2 Indexing in Numpy Array 
###### we can access an element by Index

In [16]:
demooarr=np.array([1,2,3,4,5])
print(demooarr)

[1 2 3 4 5]


In [24]:
print(demooarr[1])
print(demooarr[4])

#we can aslo do fancy Indexing
#means we can access the particular set of Indexes at same time  with vectorization
idx= [1,2,3]
print(demooarr[idx])

#we can aslo have something called boolean Indexing with the help of that we can filter an element s
#Depending Upon the condtion Like


print(arr[arr>2])
print(arr[arr%2==0])
print(arr[arr%2!=0])

2
5
[2 3 4]
[3 4 5]
[2 4]
[1 3 5]


##### We aslo have a Slicing Operation as we have In List 

In [34]:
#In slicing we pass [strIndex:EndIndex:step(Optional)]

print(arr[1:])
print(arr[1:3])
print(arr[:3])
print(arr[:])
print(arr[::2])
print(arr[::-1])
print(arr[3:1:-1])

[2 3 4 5]
[2 3]
[1 2 3]
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]
[4 3]


#### Whenever we do any Slicing Operation Lets see their diffrences In list and Numpy Array
whenever we do any slicing Operation On the List
new Copy of the list is created and Occupy the new memory
that why List tekan more time to do Operation


But Array dont create a new Copy its just create a view which is a part of the  same array
dosent Create any copy or Occupy the new Memory


In [71]:
#lets see how list react to this
num = [1,2,3,4,5,2,2,2,2]
print(num)
# create a slice list from the original list
slice_num = num[1:3]
print(slice_num)

slice_num[1]=100

print("num",num)
print("Slice Num",slice_num)



#But for the numpy array it just do changes and Create a View In the same Array
numpy_arr=np.array([1,2,3,4,5,2,2,2,2])
print("Numpy Array",numpy_arr)

slice_numpy=numpy_arr[1:3]
print(slice_numpy)
slice_numpy[1]=200
print(numpy_arr)

#You can see the the changes has been reflected in the same array
#new Copy has not created

#thats why Numpy Array are faster than List






[1, 2, 3, 4, 5, 2, 2, 2, 2]
[2, 3]
num [1, 2, 3, 4, 5, 2, 2, 2, 2]
Slice Num [2, 100]
Numpy Array [1 2 3 4 5 2 2 2 2]
[2 3]
[  1   2 200   4   5   2   2   2   2]
