In [1]:
import numpy as np

In [20]:
#Create a Numpy array of 2x2x3   two 2D array with (3x2)-->2x3x2

arr=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr,arr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)


In [29]:
#Indexing -->accesing element by Index
print("Element 4 element is -->",arr[0,1,1])
print("Element 6 element is -->",arr[0,2,1])
print("Element 2 element is -->",arr[0,1,1])
print("Element 2 element is -->",arr[0,1,0])

print("Element 7 element is -->",arr[1,2,0])
print("Element 7 element is -->",arr[1,2,1])








Element 4 element is --> 4
Element 6 element is --> 6
Element 2 element is --> 4
Element 2 element is --> 3
Element 7 element is --> 11
Element 7 element is --> 12


In [37]:
#Slicing -->access particular row or column
#We do slicing of the 3d Array
#follow the strucuture Like --> [Layer,row,Col]

print(arr[:,1,:])
print(arr[:,0,:])

#we want only first Layer

print(arr[0,1,:])
arr[0,1,:]=100
print(arr[1,1,:])
arr[1,1,:]=111

print(arr)








[[ 3  4]
 [ 9 10]]
[[1 2]
 [7 8]]
[3 4]
[ 9 10]
[[[  1   2]
  [100 100]
  [  5   6]]

 [[  7   8]
  [111 111]
  [ 11  12]]]
