##### Axes In MultiDiamentional Array
where we will have a need of MultiDiamentional Array
 when we wanted to represent an Image 
ConverImages-->numbers-->FeedTo--->MlModel


concept of the axes (axis) is Very Similar to Diamentions,we can aslo say if we are talking about axes
we are talking About Nothing But Diamentions

we Hv Diffrent Number of axies as we know

1D-> axis -->axis 0 -->lenghth
2D-> 2Axies
   axis 0->length
   axis 1->height
   
3D length,depth,height --->3 Axies
   axis 0->Depth/Number of Layers 
   axis 1->Row In each Depth
   axis 2->Columns in each Layer
   
   
┌───┬───┬───┐
│ A │ B │ C │
├───┼───┼───┤
│ D │ E │ F │
├───┼───┼───┤
│ G │ H │ I │
└───┴───┴───┘

any Operation we need to do row wise we will do it On axis 0  vertical
any Operation we need to do Column wise we will do it On axis 1 horizotal

3D array is nothing but the combination of 2d Arrays


-
  

In [2]:
#create a 2d array

In [3]:
import numpy as np

In [5]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr,arr.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] int32


In [11]:
#can we aslo calculate the sum of array
print(np.sum(arr))

78


In [14]:
#we can aslo calculate the sum of element column wise for 2D array Like
print(np.sum(arr,axis=0))

[15 18 21 24]


In [15]:
#we can aslo calculate the sum of element rows wise for 2D array Like
print(np.sum(arr,axis=1))

[10 26 42]


In [17]:
#we can aslo Perform Slicing On the 2D array
print(arr[0:2,1:2])

[[2]
 [6]]
